### ISSUE TITLE
PE-D Issues

### ISSUE THREAD

**Issue by branzuelajohn** [AY2021S2-CS2103T-T10-1/tp#343]
### Entity

- [x] #294 - Entity names are allowed to be solely numbers
- [ ] #310 - Invalid dates are accepted and silently changed to the last available date of the month

### Owner

- [x] #301 Did not specify limit on phone number input length
- [x] #318 Duplicate owner can be added if new owner does not own dogs
- [ ] #319 Duplicate owners can be added if Tags differ
- [x] #322 Invalid home address given 
- [x] #342 Suggestion for the owner entity (invalid)

### Dog

- [ ] #288 - Able to enter future dates as the date of birth of dogs
- [ ] #313 Date time format for adding of dogs is not specified in user guide
- [x] #314 Breed of dogs allow for numerical characters
- [x] #315 Duplicate dogs are allowed if sex is M and Male
- [ ] #317 Edit allows for duplicate dogs if sex is M and Male (same as #315)
- [ ] #321 Invalid date of birth #321 (same as #288)
- [ ] #330 Able to add the same dog

### Program
- [ ] #287 - Programs do not show the session date and time
- [ ] #291 - Able to add duplicate programs w/ same session and name
- [ ] #296 - Incorrect error message for add program
- [ ] #297 - Add program issue
- [ ] #306 List of programs does not show the date 
- [ ] #324 Session date and timing not displayed when a program is added (same as #287 and #306)
- [ ] #325 Error message is too generic/irrelevant to invalid inputs
- [ ] #326 Missing warning message when adding a program that has already past

### Commands
- [ ] #292 - Able to enrol programs into programs which have the same date and time
- [ ] #298 - Unable to perform any delete/edit on items not shown in the view list (INVALID)
- [x] #299 - Incorrect error message displayed for drop command
- [ ] #304 - Unable to delete dogs or owners after enrolling dog to program
- [ ] #327 Error message for "schedule" feature too generic
- [ ] #328 Dog not deleted even after owner is deleted
- [ ] #331 Unable to delete dog, with irrelevant error message shown
- [ ] #332  Error message too generic for "enrol" feature
- [x] #336 Can't edit schedule for program (invalid)
- [ ] #337 Can't find program on schedule despite matching date
- [ ] #338 editing tag overrites the whole tag instead of adding tag to existing list

### Autocomplete

- [ ] #289 - Pressing enter cancels the suggested inputs instead of confirming the input 
- [ ] #312 Enter key has to be pressed twice when List command is used anytime other than the first command

### UI

- [x] #293 - Distinction between entity types is unclear (owner/dogs/programs) -> have different colours for each entity type?
- [ ] #295 Help menu display incorrect command syntax
- [ ] #300 Schedule command not included in help window
- [ ] #303 Help window is cut off
- [x] #305 (same as #295)
- [ ] #311 (same as #295)
- [x] #329 Differentiate "Entity" vs. "Entities"
- [ ] #334 Indexing for the list that shows dogs
- [ ] #335 Indexing for list that shows programs
- [ ] #339 Issue regarding mixing ID for owner, dogs, and programs

### UG

- [ ] #290 - Unsure of the need to specify the entity type 
- [ ] #302 - Inconsistency for documentation for deletion
- [ ] #307 - Find command does not look into sub-strings? [update documentation to state that find keyword finds entire word instead of substring]
- [ ] #308 - Parameters for schedule and list not in uppercase in UG
- [ ] #309 - Link to application download URL broken in UG
- [x] #316 Indices of different entities begin at the end of previous entity
- [x] #320 Tags are not defined or explained in the user guide
- [x] #341 Cannot key in tag that is more than one word but makes use of alphanumeric characters
- [x] #333 Not enough examples given
